fun use s =
  (print ("******\n\nLoading SEAR file " ^ s ^ "\n\n******\n"); QUse.use s);
use "SEARsorts.sml";
use "SEARnewspec.sml";
use "SEARrel.sml";
use "SEARfun.sml";
use "SEARsetting.sml";
use "SEARpred_set.sml";
use "SEARNarith.sml";
use "SEARZarith.sml";
use "SEARFiniteness.sml";
use "SEARList.sml";
use "SEARfm.sml";
use "SEARUF.sml";
use "SEARmmmt.sml";
use "SEARllist.sml";
use "SEARGrp.sml";
use "SEARexamplecol.sml";
use "Upows'.sml";
